### ISSUE TITLE
Chrome border bug

### ISSUE THREAD

**Issue by EdAdaptive** [AdaptiveConsulting/ui-kit-2022#157]
(Ed) - There's an issue where a border will appear to be thicker than it actually is.  This is happening on my machine (Windows 10 version 21H2, Chrome Version 107.0.5304.88 (Official Build) (64-bit)).  I've tested it on another Windows 10 machine (Version 20H2) with the same Chrome version and the bug doesn't appear.

- May be a Chromium issue since I have the issue in Chrome and Edge, but not in Firefox.  Haven't tested other browsers besides these.
- (Ed) Only able to replicate it on my machine as far as I know
- Seems related to resizing since the bug will jump to another border, or disappear, as the screen shrinks / increases

UI Kit

![Image](https://user-images.githubusercontent.com/106989342/199023431-83e8bfea-1f28-45a2-8ee6-59a3e2429f92.png)

MUI Table Docs

![Image](https://user-images.githubusercontent.com/106989342/199023583-2fe4f783-f9b0-44cc-9a1b-16aa290b6f4d.png)

**Comment by Honglin-Lu** [comment]
(Honglin) I got the same border issue as Ed. And my machine (Windows 10 pro version 21H2, Chrome Version 108.0.5359.71 (Official Build) (64-bit)). 

![Image](https://user-images.githubusercontent.com/56696843/205136938-c10fa000-1fed-4113-91d6-68a7a4671255.png)

But the border issue is gone when I switch this page to my bigger screen(27 inches).
