### ISSUE TITLE
TextSearch dropdown persists after switching stories

### ISSUE THREAD

**Issue by iandilling-adaptive** [AdaptiveConsulting/ui-kit-2022#173]
https://adaptiveconsulting.github.io/ui-kit-2022/?path=/story/design-system-ticker-search--ticker-search

The always open dropdown will persist even when switching stories. This happens because MUI by default will mount the dropdown outside the Storybook viewport. There is a way to toggle this in the component.

**Comment by chuck-adaptive** [comment]
The text search has a prop to attach the dropdown to the text search component, as opposed to an outside div (which is what it's doing now)
