### ISSUE TITLE
Export a Hello World component as our "UI Kit"

### ISSUE THREAD

**Issue by chuck-adaptive** [AdaptiveConsulting/ui-kit-2022#3]
We are awaiting delivery of the kit from UX. For now, let's prep the codebase to be closer to what we want it to be, structurally.

Let's make the kit 1 component, a "Hello World" div

As a developer, I can import that "Hello World" div locally & see it in a new React app

**Comment by EdAdaptive** [comment]
The local testing will be done in the ["Configure the project to build & deploy as a node module"](https://github.com/chuck-adaptive/ui-kit-2022/issues/16) ticket.
